name: API Status Badge

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-api-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check API Status
        id: api_status
        run: |
          response=$(curl --write-out "%{http_code}\n" --silent --output /dev/null https://otso.veistera.com/translate)
          if [ "$response" -eq 200 ]; then
            echo "![API Status](https://img.shields.io/badge/API%20Status-Online-brightgreen)" > api-status-badge.md
            echo "online" > api-status.txt
          else
            echo "![API Status](https://img.shields.io/badge/API%20Status-Offline-red)" > api-status-badge.md
            echo "offline" > api-status.txt
          fi

      - name: Check if status has changed
        id: status_check
        run: |
          if [ -f api-status.txt ]; then
            last_status=$(cat api-status.txt)
          else
            last_status="unknown"
          fi

          current_status=$(cat api-status.txt)
          
          if [ "$last_status" != "$current_status" ]; then
            echo "Status changed"
            echo "changed" > change.txt
          else
            echo "No status change"
            echo "unchanged" > change.txt
          fi

      - name: Commit changes if status changed
        if: steps.status_check.outputs.change == 'changed'
        run: |
          git config --global user.email "you@example.com"  # Replace with your email
          git config --global user.name "Your Name"  # Replace with your name
          git add api-status-badge.md api-status.txt
          git commit -m "Update API status badge"
          git push
