name: API Status Badge

permissions: write-all

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  check-api-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check API Status and Create Badge
        id: api_status
        run: |
          response=$(curl --write-out "%{http_code}\n" --silent --output /dev/null https://otso.veistera.com/translate)
          echo "Received HTTP response: $response"

          if [ "$response" -eq 200 ]; then
            echo "API Status: Online"
            echo "![API Status](https://img.shields.io/badge/API%20Status-Online-brightgreen)" > api-status-badge.md
            echo "online" > api-status.txt
          else
            echo "API Status: Offline (HTTP Code: $response)"
            echo "![API Status](https://img.shields.io/badge/API%20Status-Offline-red)" > api-status-badge.md
            echo "offline" > api-status.txt
          fi
          
          # Output status for debugging
          echo "Current API status written to file: $(cat api-status.txt)"

      - name: Commit changes
        run: |
          git config --global user.name 'Otso Veisterä'
          git config --global user.email 'otso.veistera@gmail.com'

          # Check if there are changes to commit
          if [[ -n $(git status --porcelain) ]]; then
            git add api-status-badge.md api-status.txt
            git commit -m "Update API status badge"
            git push
          else
            echo "No changes to commit."
